# Site settings
title: Kate Montgomery
email: katharine.montgomery@gmail.com
description: "Junior full stack developer and soon to be graduate of the General Assembly Web Development Immersive course. Come back soon to see my portfolio"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _katemontgomery
github_username:  katemont

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['README.md']

paginate: 1

